//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipio
    {
        public System.Guid IdMunicipio { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public System.Guid IdDepartamento { get; set; }
    
        public virtual Departamento Departamento { get; set; }
    }
}
