//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioSistema
    {
        public System.Guid IdUsuarioSistema { get; set; }
        public System.Guid IdUsuario { get; set; }
        public System.Guid IdRolSistema { get; set; }
        public bool EsActivo { get; set; }
    
        public virtual RolSistema RolSistema { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
